build:
  image: bjodah/bjodahimg16dev:v1.3
  commands:
    - python3 -m pip install -r requirements.txt
    - python3 setup.py develop
    - ./scripts/ci.sh symvarsub
    - (cd examples/; ipython3 nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: symvarsub
    source: deploy/
    target: ~
    recursive: true
    delete: false
