image: bjodah/bjodahimg:latest
git:
    path: github.com/bjodah/symvarsub
env:
  - MY_SERVER=symvarsub@hera.physchem.kth.se
script:
  - if [[ "$DRONE_BRANCH" =~ ^v[0-9]+.[0-9]?* ]]; then export SYMVARSUB_RELEASE_VERSION=$DRONE_BRANCH; echo ${SYMVARSUB_RELEASE_VERSION} | tail -c +2 > __conda_version__.txt; fi
  - pip install -r requirements.txt
  - pip3 install -r requirements.txt
  - python2.7 setup.py install
  - rm -r build/
  - python3.4 setup.py install
  - PYTHONPATH=$(pwd) ./scripts/run_tests.sh --cov symvarsub --cov-report html
  - python2 setup.py sdist
  - pip install dist/*.tar.gz
  - ./scripts/generate_docs.sh
  - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
  - ssh "${MY_SERVER}" "mkdir -p ~/public_html/$DRONE_BRANCH"
  - scp -r doc/_build/html dist/* htmlcov/ examples/ ${MY_SERVER}:~/public_html/$DRONE_BRANCH
  - touch doc/_build/html/.nojekyll
  - git config --global user.name "drone"
  - git config --global user.email ${MY_SERVER}
  - if [[ "$DRONE_BRANCH" == "master" ]]; then ./scripts/github_upload.sh doc/_build/html bjodah symvarsub gh-pages; fi
