language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get install -qq gfortran python-numpy cython python-pytest python-argh"
  - "pip install -r requirements.txt"
install:
  - "python setup.py install"
script: "py.test ."
notifications:
  email: false
