package:
    name: symvarsub
    version: 0.1.0.git

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - python
        - numpy
        - cython
    run:
        - python
        - numpy

test:
    imports:
        - symvarsub
    requires:
        - pytest

about:
    home: https://github.com/bjodah/symvarsub
    license: BSD
